spring:
    data:
        jpa:
            repositories:
                bootstrap-mode: default
                enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            auto-commit: false
            connection-test-query: select 1
            connection-timeout: 3000
            idle-timeout: 30000
            max-lifetime: 60000
            maximum-pool-size: 10
            minimum-idle: 1
            pool-name: eshopConnectionPooling
            transaction-isolation: TRANSACTION_READ_COMMITTED
            username: sa
            password: sa
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/scytalis-eshop?reWriteBatchedInserts=true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                batch_versioned_data: true
                connection:
                    # Sources
                    # https://vladmihalcea.com/spring-transaction-connection-management
                    # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions/
                    # handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
                    provider_disables_autocommit: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    batch_size: 100
                format_sql: true
                order_inserts: true
                order_updates: true
                query:
                    in_clause_parameter_padding: true
                generate_statistics: true # NOT a production setting
                session:
                    events:
                        log:
                            LOG_QUERIES_SLOWER_THAN_MS: 10 # NOT a production setting
        show-sql: false
    sql:
        init:
            # Mode to apply when determining if DataSource initialization should be performed using the available DDL (schema
            # .sql) and DML (data.sql) scripts.
            mode: never
            platform: postgresql
